// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxxbzxcshywgzagbifvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4eGJ6eGNzaHl3Z3phZ2JpZnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMjI3NzcsImV4cCI6MjA3NTg5ODc3N30.dgDoNV7Ifr83d_SFo_a1xtBbMbMgRYgjfub672zEy20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});